-- AlterTable
ALTER TABLE "License" ADD COLUMN     "keysPerMinute" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "machineEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "priceUsd" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "simulatedRoi" DOUBLE PRECISION,
ADD COLUMN     "tier" TEXT NOT NULL DEFAULT 'STARTER';
